import type { NumberToBigInt, PowerBigInt, RandomEngineTraits, SubtractBigInt, TypedRandomEngine } from '../concepts';
import type { SeedSequence, RandomEngine, SeedResult, UInt, UIntType, UnsignedLongLong, Size, UIntWithLiteralValue } from '../typings';
import { UINT64_MAX, UInt32Type, RandomErrorCode, RandomError } from '../typings';

export interface MersenneTwisterEngineDefinition<T extends UInt> {
  wordSize: Size;
  stateSize: Size;
  shiftSize: Size;
  maskBits: Size;
  xorMask: T;
  temperingU: Size;
  temperingD: T;
  temperingS: Size;
  temperingB: T;
  temperingT: Size;
  temperingC: T;
  temperingL: Size;
  initializationMultiplier: T;
}

export type MersenneMax<WordSize extends number> =
  number extends WordSize
    ? bigint
    : SubtractBigInt<PowerBigInt<2n, NumberToBigInt<WordSize>>, 1n>;

/**
 * Type-level range information for one Mersenne Twister specialization.
 *
 * @typeParam Type Result type generated by the engine.
 * @typeParam Definition Specialization parameters.
 */
export type MersenneTwisterEngineTraits<
  Type extends UInt,
  Definition extends MersenneTwisterEngineDefinition<Type>,
> = RandomEngineTraits<0n, MersenneMax<Definition['wordSize']>>;

/**
 * Constructor type for one Mersenne Twister engine specialization.
 *
 * @typeParam Type Result type generated by the engine.
 * @typeParam Traits Type-level range information derived from the
 * specialization parameters.
 */
export interface MersenneTwisterEngineConstructor<Type extends UInt, Traits extends RandomEngineTraits = RandomEngineTraits> {
  new(): MersenneTwisterEngine<Type> & TypedRandomEngine<Type, Traits>;
  new(value: Type): MersenneTwisterEngine<Type> & TypedRandomEngine<Type, Traits>;
  new(sequence: SeedSequence): MersenneTwisterEngine<Type> & TypedRandomEngine<Type, Traits>;
  new(other: MersenneTwisterEngine<Type>): MersenneTwisterEngine<Type> & TypedRandomEngine<Type, Traits>;

  readonly resultType: UIntType<Type>;
  readonly wordSize: Size;
  readonly stateSize: Size;
  readonly shiftSize: Size;
  readonly maskBits: Size;
  readonly xorMask: Type;
  readonly temperingU: Size;
  readonly temperingD: Type;
  readonly temperingS: Size;
  readonly temperingB: Type;
  readonly temperingT: Size;
  readonly temperingC: Type;
  readonly temperingL: Size;
  readonly initializationMultiplier: Type;
  readonly defaultSeed: Type;

  min(): UIntWithLiteralValue<Type, Traits['minimum']>;
  max(): UIntWithLiteralValue<Type, Traits['maximum']>;
}

/**
 * `MersenneTwisterEngine` is a random number engine based on the
 * Mersenne Twister algorithm.
 *
 * ### Template parameters
 *
 * `T` is the result type generated by the engine.
 *
 * `wordSize` corresponds to `w`.
 *
 * `stateSize` corresponds to `n`.
 *
 * `shiftSize` corresponds to `m`.
 *
 * `maskBits` corresponds to `r`.
 *
 * `xorMask` corresponds to `a`.
 *
 * `temperingU` corresponds to `u`.
 *
 * `temperingD` corresponds to `d`.
 *
 * `temperingS` corresponds to `s`.
 *
 * `temperingB` corresponds to `b`.
 *
 * `temperingT` corresponds to `t`.
 *
 * `temperingC` corresponds to `c`.
 *
 * `temperingL` corresponds to `l`.
 *
 * `initializationMultiplier` corresponds to `f`.
 *
 * ### Generator properties
 *
 * The state of a `MersenneTwisterEngine` object is of size `n` and consists
 * of a sequence of `n` values of the result type. All state subscripts are
 * taken modulo `n`.
 *
 * The transition algorithm is:
 *
 * `Y = (X[i - n] & ((2^w - 1) - (2^r - 1))) | (X[i + 1 - n] & (2^r - 1))`
 *
 * `X[i] = X[i + m - n] ^ (Y >> 1) ^ (a * (Y & 1))`
 *
 * The generation algorithm is:
 *
 * `z = X[i]`
 *
 * `z = z ^ ((z >> u) & d)`
 *
 * `z = z ^ ((z << s) & b)`
 *
 * `z = z ^ ((z << t) & c)`
 *
 * `z = z ^ (z >> l)`
 *
 * The pseudo-random number generated is `z`.
 *
 * ### Predefined specializations
 *
 * Two commonly used parameter sets are:
 *
 * - `mt19937`: word size `32`, state size `624`, shift size `397`,
 *   mask bits `31`, xor mask `0x9908b0df`, tempering parameters
 *   `u=11`, `d=0xffffffff`, `s=7`, `b=0x9d2c5680`, `t=15`,
 *   `c=0xefc60000`, `l=18`, and initialization multiplier `1812433253`.
 * - `mt19937_64`: word size `64`, state size `312`, shift size `156`,
 *   mask bits `31`, xor mask `0xb5026f5aa96619e9`, tempering parameters
 *   `u=29`, `d=0x5555555555555555`, `s=17`,
 *   `b=0x71d67fffeda60000`, `t=37`,
 *   `c=0xfff7eee000000000`, `l=43`, and initialization multiplier
 *   `6364136223846793005`.
 *
 * ### Requirements
 *
 * The following relations shall hold:
 *
 * - `0 < m`
 * - `m <= n`
 * - `2u < w`
 * - `r <= w`
 * - `u <= w`
 * - `s <= w`
 * - `t <= w`
 * - `l <= w`
 * - `w <= numeric_limits<UIntType>::digits`
 * - `a <= 2^w - 1`
 * - `b <= 2^w - 1`
 * - `c <= 2^w - 1`
 * - `d <= 2^w - 1`
 * - `f <= 2^w - 1`
 *
 * ### Member types
 *
 * The result type is represented by `T`.
 *
 * ### Data members
 *
 * - `resultType` is the runtime representation of `result_type`.
 * - `wordSize` is `w`.
 * - `stateSize` is `n`.
 * - `shiftSize` is `m`.
 * - `maskBits` is `r`.
 * - `xorMask` is `a`.
 * - `temperingU` is `u`.
 * - `temperingD` is `d`.
 * - `temperingS` is `s`.
 * - `temperingB` is `b`.
 * - `temperingT` is `t`.
 * - `temperingC` is `c`.
 * - `temperingL` is `l`.
 * - `initializationMultiplier` is `f`.
 * - `defaultSeed` is `5489`.
 *
 * These members are static and belong to an engine specialization.
 *
 * ### Member functions
 *
 * #### Construction and Seeding
 *
 * - The constructor constructs the engine.
 * - `seed()` sets the current state of the engine.
 *
 * #### Generation
 *
 * - `next()` advances the engine's state and returns the generated value.
 * - `discard()` advances the engine's state by a specified amount.
 *
 * #### Characteristics
 *
 * - `min()` gets the smallest possible value in the output range.
 * - `max()` gets the largest possible value in the output range.
 *
 * ### Non-member functions
 *
 * Equality compares the internal states of two pseudo-random number engines.
 *
 * @typeParam T Result type generated by the engine.
 *
 * @see https://en.cppreference.com/cpp/numeric/random/mersenne_twister_engine
 */
export abstract class MersenneTwisterEngine<T extends UInt> implements RandomEngine<T> {
  public static readonly defaultSeed: UInt = 5489n as UInt;

  public static readonly wordSize = 0 as Size;
  public static readonly stateSize = 0 as Size;
  public static readonly shiftSize = 0 as Size;
  public static readonly maskBits = 0 as Size;
  public static readonly xorMask: UInt = 0n as UInt;
  public static readonly temperingU = 0 as Size;
  public static readonly temperingD: UInt = 0n as UInt;
  public static readonly temperingS = 0 as Size;
  public static readonly temperingB: UInt = 0n as UInt;
  public static readonly temperingT = 0 as Size;
  public static readonly temperingC: UInt = 0n as UInt;
  public static readonly temperingL = 0 as Size;
  public static readonly initializationMultiplier: UInt =
    0n as UInt;

  private state: T[];
  private index: number;

  private readonly wordMask: bigint;
  private readonly lowerMask: bigint;
  private readonly upperMask: bigint;

  /**
   * Constructs the engine with `defaultSeed`.
   */
  public constructor();

  /**
   * Constructs the engine with a seed value.
   *
   * @param value Seed value used to initialize the state.
   */
  public constructor(value: T);

  /**
   * Constructs the engine with a seed sequence.
   *
   * @param seq Seed sequence used to initialize the state.
   */
  public constructor(seq: SeedSequence);

  /**
   * Constructs the engine as a copy of another engine.
   *
   * @param other Engine whose state is copied.
   */
  public constructor(other: MersenneTwisterEngine<T>);

  public constructor(
    value?: T | SeedSequence | MersenneTwisterEngine<T>,
  ) {
    const type = this.constructor as MersenneTwisterEngineConstructor<T>;

    this.wordMask = (1n << BigInt(type.wordSize)) - 1n;
    this.lowerMask = (1n << BigInt(type.maskBits)) - 1n;
    this.upperMask = this.wordMask ^ this.lowerMask;

    this.state = new Array<T>(type.stateSize);
    this.index = type.stateSize;

    if (value instanceof MersenneTwisterEngine) {
      if (value.constructor !== this.constructor) {
        throw new RandomError(
          RandomErrorCode.INVALID_ARGUMENT,
          'The engine types must match.',
          {
            expected: this.constructor.name,
            actual: value.constructor.name,
          },
        );
      }

      this.state = value.state.slice();
      this.index = value.index;
      return;
    }

    if (value === undefined) {
      this.seed(type.defaultSeed);
      return;
    }

    if (typeof value === 'bigint') {
      this.seed(value);
      return;
    }

    this.seed(value);
  }

  /**
   * Returns the smallest possible value in the output range.
   *
   * @returns `0`.
   */
  public static min(): UInt {
    return 0n as UInt;
  }

  /**
   * Returns the largest possible value in the output range.
   *
   * @returns `2^w - 1`.
   */
  public static max(): UInt {
    const type = this as typeof MersenneTwisterEngine;

    if (type.wordSize === 0) {
      throw new RandomError(
        RandomErrorCode.INVALID_STATE,
        'The engine parameters are not available on the base engine.',
      );
    }

    return ((1n << BigInt(type.wordSize)) - 1n) as UInt;
  }

  /**
   * Sets the state to `defaultSeed`.
   */
  public seed(): void;

  /**
   * Sets the state using a seed value.
   *
   * @param value Seed value used to set the state.
   */
  public seed(value: T): void;

  /**
   * Sets the state using a seed sequence.
   *
   * @param seq Seed sequence used to set the state.
   */
  public seed(seq: SeedSequence): void;

  public seed(valueOrSequence?: T | SeedSequence): void {
    const type = this.constructor as MersenneTwisterEngineConstructor<T>;

    if (valueOrSequence === undefined) {
      this.seedValue(type.defaultSeed);
      return;
    }

    if (typeof valueOrSequence === 'bigint') {
      this.seedValue(valueOrSequence);
      return;
    }

    this.seedSequence(valueOrSequence);
  }

  /**
   * Advances the state and returns the generated value.
   *
   * @returns The generated value.
   */
  public next(): T {
    const { stateSize } = this.constructor as MersenneTwisterEngineConstructor<T>;

    if (this.index >= stateSize) {
      this.twist();
      this.index = 0;
    }

    const value = this.state[this.index];

    if (value === undefined) {
      throw new RandomError(
        RandomErrorCode.INVALID_STATE,
        'The engine state is not initialized.',
      );
    }

    const result = this.temper(value);

    this.index += 1;

    return result;
  }

  /**
   * Advances the state by `z` generations.
   *
   * @param z Number of generations to discard.
   */
  public discard(z: UnsignedLongLong): void {
    if (z < 0n || z > UINT64_MAX) {
      throw new RandomError(
        RandomErrorCode.OUT_OF_RANGE,
        'The discard count is outside the unsigned long long range.',
        { z },
      );
    }

    const type = this.constructor as MersenneTwisterEngineConstructor<T>;
    const stateSize = type.stateSize;
    const position = BigInt(this.index) + z;

    if (position <= BigInt(stateSize)) {
      this.index = Number(position);
      return;
    }

    const remaining = position - BigInt(stateSize);
    const twists = remaining / BigInt(stateSize);
    const remainder = remaining % BigInt(stateSize);

    for (let i = 0n; i < twists; i += 1n) {
      this.twist();
    }

    if (remainder === 0n) {
      this.index = stateSize;
      return;
    }

    this.twist();
    this.index = Number(remainder);
  }

  /**
   * Compares the states of two engines.
   *
   * @param other Engine to compare.
   * @returns `true` if the states are equal.
   */
  public equals(other: MersenneTwisterEngine<T>): boolean {
    if (this.constructor !== other.constructor ||
        this.index !== other.index ||
        this.state.length !== other.state.length) {
      return false;
    }

    for (let i = 0; i < this.state.length; i += 1) {
      if (this.state[i] !== other.state[i]) {
        return false;
      }
    }

    return true;
  }

  private seedValue(value: T): void {
    const type = this.constructor as MersenneTwisterEngineConstructor<T>;
    const nextState = new Array<T>(type.stateSize);
    let x = (value as bigint) & this.wordMask;

    nextState[0] = x as T;

    const multiplier = type.initializationMultiplier as bigint;
    const shift = BigInt(type.wordSize - 2);

    for (let i = 1; i < type.stateSize; i += 1) {
      x = (multiplier * (x ^ (x >> shift)) + BigInt(i)) & this.wordMask;
      nextState[i] = x as T;
    }

    this.state = nextState;
    this.index = type.stateSize;
  }

  private seedSequence(seq: SeedSequence): void {
    const { wordSize, stateSize } = this.constructor as MersenneTwisterEngineConstructor<T>;
    const k = Math.ceil(wordSize / 32);
    const data = new Array<SeedResult>(stateSize * k)

    seq.generate(data);

    const nextState = new Array<T>(stateSize);

    for (let i = 0; i < stateSize; ++i) {
      let x = 0n;
      for (let j = 0; j < k; ++j) {
        const value = data[i * k + j];
        if (value === undefined) {
          throw new RandomError(
            RandomErrorCode.INVALID_SEED_SEQUENCE,
            'The seed sequence did not generate enough values.',
            { index: i * k + j }
          );
        }

        UInt32Type.cast(value as bigint);

        x |= (value as bigint) << BigInt(32 * j);
      }

      nextState[i] = (x & this.wordMask) as T;
    }

    let zero = ((nextState[0]! as bigint) & this.upperMask) === 0n;

    for (let i = 1; i < stateSize && zero; ++i) {
      zero = (nextState[i]! as bigint) === 0n;
    }

    if (zero) {
      nextState[0] = (1n << BigInt(wordSize - 1)) as T;
    }

    this.state = nextState;
    this.index = stateSize;
  }

  private twist(): void {
    const { stateSize, shiftSize, xorMask } = this.constructor as MersenneTwisterEngineConstructor<T>;
    const a = xorMask as bigint;

    for (let i = 0; i < stateSize; i += 1) {
      const x = this.state[i];
      const xNext = this.state[(i + 1) % stateSize];
      const xM = this.state[(i + shiftSize) % stateSize];

      if (x === undefined || xNext === undefined || xM === undefined) {
        throw new RandomError(
          RandomErrorCode.INVALID_STATE,
          'The engine state is not initialized.',
        );
      }

      const y = ((x as bigint) & this.upperMask) |
        ((xNext as bigint) & this.lowerMask);

      const alpha = a * (y & 1n);

      this.state[i] = (((xM as bigint) ^ (y >> 1n) ^ alpha) & this.wordMask) as T;
    }
  }

  private temper(value: T): T {
    const type = this.constructor as MersenneTwisterEngineConstructor<T>;

    let z = value as bigint;
    z ^= (z >> BigInt(type.temperingU)) & (type.temperingD as bigint);
    z ^= ((z << BigInt(type.temperingS)) & this.wordMask) & (type.temperingB as bigint);
    z ^= ((z << BigInt(type.temperingT) & this.wordMask)) & (type.temperingC as bigint);
    z ^= z >> BigInt(type.temperingL);

    return (z & this.wordMask) as T
  }
}

function validateMersenneTwisterEngineDefinition<T extends UInt>(
  resultType: UIntType<T>,
  { wordSize, stateSize, shiftSize, maskBits, xorMask, initializationMultiplier,
    temperingU, temperingS, temperingT, temperingL, 
    temperingB, temperingC, temperingD }: MersenneTwisterEngineDefinition<T>,
): void {
  const resultTypeBits = (resultType.modulus - 1n).toString(2).length;
  const integer = (value: number): boolean => Number.isSafeInteger(value);

  if (!integer(wordSize) || wordSize > resultTypeBits) {
    throw new RandomError(
      RandomErrorCode.INVALID_ARGUMENT,
      'The word size is invalid.',
      { wordSize }
    );
  }

  if (!integer(stateSize) || stateSize < 1) {
    throw new RandomError(
      RandomErrorCode.INVALID_ARGUMENT,
      'The state size is invalid.',
      { stateSize }
    );
  }

  if (!integer(shiftSize) || shiftSize < 1 || shiftSize > stateSize) {
    throw new RandomError(
      RandomErrorCode.INVALID_ARGUMENT,
      'The shift size is invalid.',
      { shiftSize }
    );
  }

  if (!integer(maskBits) || maskBits < 0 || maskBits > wordSize) {
    throw new RandomError(
      RandomErrorCode.INVALID_ARGUMENT,
      'The mask bits are invalid.',
      { maskBits }
    );
  }

  if (!integer(temperingU) || temperingU < 0 || temperingU > wordSize ||
      !integer(temperingS) || temperingS < 0 || temperingS > wordSize ||
      !integer(temperingT) || temperingT < 0 || temperingT > wordSize ||
      !integer(temperingL) || temperingL < 0 || temperingL > wordSize) {
    throw new RandomError(
      RandomErrorCode.INVALID_ARGUMENT,
      'The tempering parameters are invalid.',
    );
  }

  if (2 * temperingU >= wordSize) {
    throw new RandomError(
      RandomErrorCode.INVALID_ARGUMENT,
      'The tempering parameters are invalid.',
    );
  }

  const wordMask = (1n << BigInt(wordSize)) - 1n;
  const parameters: ReadonlyArray<readonly [string, bigint]> = [
    ['xorMask', xorMask as bigint],
    ['temperingD', temperingD as bigint],
    ['temperingB', temperingB as bigint],
    ['temperingC', temperingC as bigint],
    ['initializationMultiplier', initializationMultiplier as bigint]
  ];

  for (const [name, value] of parameters) {
    if (value < 0n || value > wordMask) {
      throw new RandomError(
        RandomErrorCode.OUT_OF_RANGE,
        `The ${name} is outside the word range.`,
        { [name]: value }
      );
    }
  }
}

export function defineMersenneTwisterEngine<
  Type extends UInt,
  const Definition extends MersenneTwisterEngineDefinition<Type>,
>(
  resultType: UIntType<Type>,
  definition: Definition,
): MersenneTwisterEngineConstructor<
  Type,
  MersenneTwisterEngineTraits<Type, Definition>
> {
  validateMersenneTwisterEngineDefinition(resultType, definition);

  type Traits = MersenneTwisterEngineTraits<Type, Definition>;

  class Engine extends MersenneTwisterEngine<Type> {
    public static readonly resultType = resultType;
    public static readonly wordSize = definition.wordSize;
    public static readonly stateSize = definition.stateSize;
    public static readonly shiftSize = definition.shiftSize;
    public static readonly maskBits = definition.maskBits;
    public static readonly xorMask = definition.xorMask;
    public static readonly temperingU = definition.temperingU;
    public static readonly temperingD = definition.temperingD;
    public static readonly temperingS = definition.temperingS;
    public static readonly temperingB = definition.temperingB;
    public static readonly temperingT = definition.temperingT;
    public static readonly temperingC = definition.temperingC;
    public static readonly temperingL = definition.temperingL;
    public static readonly initializationMultiplier = definition.initializationMultiplier;
    public static readonly defaultSeed = 5489n as Type;

    public static override min(): UIntWithLiteralValue<Type, Traits['minimum']> {
      return 0n as UIntWithLiteralValue<Type, Traits['minimum']>;
    }

    public static override max(): UIntWithLiteralValue<Type, Traits['maximum']> {
      return ((1n << BigInt(this.wordSize)) - 1n) as UIntWithLiteralValue<Type, Traits['maximum']>;
    }
  }

  return Object.freeze(Engine) as unknown as MersenneTwisterEngineConstructor<Type, Traits>;
}
