import type { SeedSequence, UniformRandomBitGenerator } from '../random/interfaces';
import type { SeedResult, UInt, UInt32, UnsignedLongLong } from '../random/types';
import { UINT32_MAX, UINT64_MAX } from '../random/types';
import { RANDOM_ERROR_CODES, RandomError } from '../random/error';

type ResultBits = 32 | 64;
const resultBits64 = new WeakSet<Function>();
const getResultBits = (type: Function): ResultBits => (
  resultBits64.has(type) ? 64 : 32
);

export interface LinearCongruentialEngineDefinition<T extends UInt> {
  multiplier: T;
  increment: T;
  modulus: T;
  defaultSeed: T;
  resultBits: ResultBits;
}

export interface LinearCongruentialEngineConstructor<T extends UInt> {
  new(): LinearCongruentialEngine<T>;
  new(value: T): LinearCongruentialEngine<T>;
  new(seq: SeedSequence): LinearCongruentialEngine<T>;
  new(other: LinearCongruentialEngine<T>): LinearCongruentialEngine<T>;

  readonly multiplier: T;
  readonly increment: T;
  readonly modulus: T;
  readonly defaultSeed: T;

  min(): T;
  max(): T;
}

/**
 * `LinearCongruentialEngine` is a random number engine based on a linear
 * congruential generator (LCG).
 *
 * ### Template parameters
 *
 * `T` is the result type generated by the engine.
 *
 * ### Generator properties
 *
 * The state size of `LinearCongruentialEngine` is `1`, and the state consists
 * of a single integer.
 *
 * The actual modulus `m0` is defined as follows:
 *
 * - If `modulus` is not zero, `m0` is `modulus`.
 * - If `modulus` is zero, `m0` is one greater than the maximum value
 *   representable by the result type. This value does not necessarily fit
 *   in the result type.
 *
 * The transition algorithm is:
 *
 * `TA(xi) = (a * xi + c) mod m0`
 *
 * The generation algorithm is:
 *
 * `GA(xi) = (a * xi + c) mod m0`
 *
 * The pseudo-random number generated with the current state is also the
 * successor state.
 *
 * ### Predefined specializations
 *
 * Two commonly used parameter sets are:
 *
 * - `minstd_rand0`: multiplier `16807`, increment `0`, modulus `2147483647`.
 * - `minstd_rand`: multiplier `48271`, increment `0`, modulus `2147483647`.
 *
 * `minstd_rand0` was discovered in 1969 by Lewis, Goodman and Miller and
 * adopted as the "Minimal standard" in 1988 by Park and Miller.
 *
 * `minstd_rand` is the newer "Minimum standard", recommended by Park,
 * Miller, and Stockmeyer in 1993.
 *
 * ### Member types
 *
 * The result type is represented by the type parameter `T`.
 *
 * ### Data members
 *
 * - `multiplier` is the multiplier term `a`.
 * - `increment` is the increment term `c`.
 * - `modulus` is the modulus term `m`.
 * - `defaultSeed` is `1`.
 *
 * These members are static and belong to an engine specialization.
 *
 * ### Member functions
 *
 * #### Construction and Seeding
 *
 * - The constructor constructs the engine.
 * - `seed()` sets the current state of the engine.
 *
 * #### Generation
 *
 * - `next()` advances the engine's state and returns the generated value.
 * - `discard()` advances the engine's state by a specified amount.
 *
 * #### Characteristics
 *
 * - `min()` gets the smallest possible value in the output range.
 * - `max()` gets the largest possible value in the output range.
 *
 * ### Non-member functions
 *
 * Equality compares the internal states of two pseudo-random number engines.
 *
 * @typeParam T Result type generated by the engine.
 * @see https://en.cppreference.com/cpp/numeric/random/linear_congruential_engine
 */
export abstract class LinearCongruentialEngine<T extends UInt>
  implements UniformRandomBitGenerator<T> {
  public static readonly multiplier: UInt = 0n as UInt;
  public static readonly increment: UInt = 0n as UInt;
  public static readonly modulus: UInt = 0n as UInt;
  public static readonly defaultSeed: UInt = 1n as UInt;

  private state: T = 0n as T;
  private readonly actualModulus: bigint;

  /**
   * Constructs the engine.
   *
   * The default constructor seeds the engine with `defaultSeed`.
   *
   * @returns The constructed engine.
   */
  public constructor();

  /**
   * Constructs the engine with a seed value.
   *
   * The initial state is determined as follows:
   *
   * - If `c % m == 0` and `value % m == 0`, the state is `1`.
   * - Otherwise, the state is `value % m`.
   *
   * @param value Seed value used to initialize the internal state.
   */
  public constructor(value: T);

  /**
   * Constructs the engine with a seed sequence.
   *
   * Let `k = floor(log2(m) / 32) + 1`.
   * An array of `k + 3` 32-bit values is generated by the seed sequence.
   * Let `S` be the sum of `a[j + 3] * 2^(32 * j)` for
   * `j` in `[0, k)`, reduced modulo `m`.
   *
   * - If `c % m == 0` and `S == 0`, the state is `1`.
   * - Otherwise, the state is `S`.
   *
   * @param seq Seed sequence used to initialize the internal state.
   */
  public constructor(seq: SeedSequence);

  /**
   * Constructs the engine as a copy of another engine.
   *
   * Upon construction, the two engines have equivalent internal states.
   *
   * @param other Engine to copy.
   */
  public constructor(other: LinearCongruentialEngine<T>);

  public constructor(value?: T | SeedSequence | LinearCongruentialEngine<T>) {
    const type = this.constructor as LinearCongruentialEngineConstructor<T> & typeof LinearCongruentialEngine;

    this.actualModulus = this.getActualModulus(type);
    this.validateParameters(type);
  
    if (value instanceof LinearCongruentialEngine) {
      if (value.constructor !== this.constructor) {
        throw new RandomError(
          RANDOM_ERROR_CODES.INVALID_ARGUMENT,
          'The engine types must match.',
          {
            expected: this.constructor.name,
            actual: value.constructor.name,
          },
        );
      }

      this.state = value.state;
      return;
    }

    if (value === undefined) {
      this.seed(type.defaultSeed);
      return;
    }

    if (typeof value === 'bigint') {
      this.seed(value);
      return;
    }

    this.seed(value);
  }

  /**
   * Gets the smallest possible value in the output range.
   *
   * The result is `1` if the increment is zero, otherwise `0`.
   *
   * @returns The smallest possible generated value.
   */
  public static min(): UInt {
    return (this.increment === 0n ? 1n : 0n) as UInt;
  }

  /**
   * Gets the largest possible value in the output range.
   *
   * The result is `modulus - 1`.
   *
   * @returns The largest possible generated value.
   */
  public static max(): UInt {
    if (this.modulus === 0n) {
      return (getResultBits(this) === 32 ? UINT32_MAX : UINT64_MAX) as UInt;
    }

    return (this.modulus - 1n) as UInt;
  }

  /**
   * Sets the current state of the engine.
   */
  public seed(): void;

  /**
   * Sets the current state of the engine with a seed value.
   *
   * The state is initialized using the same procedure as the constructor
   * taking a seed value.
   *
   * @param value Seed value used to set the state.
   */
  public seed(value: T): void;

  /**
   * Sets the current state of the engine with a seed sequence.
   *
   * The state is initialized using the same procedure as the constructor
   * taking a seed sequence.
   *
   * @param seq Seed sequence used to set the state.
   */
  public seed(seq: SeedSequence): void;

  public seed(valueOrSequence?: T | SeedSequence): void {
    const type = this.constructor as LinearCongruentialEngineConstructor<T> & typeof LinearCongruentialEngine;

    if (valueOrSequence === undefined) {
      this.state = this.seedValue(type.defaultSeed);
      return;
    }

    if (typeof valueOrSequence === 'bigint') {
      this.state = this.seedValue(valueOrSequence);
      return;
    }

    this.seedSequence(valueOrSequence);
  }

  /**
   * Advances the state of the engine and generates a pseudo-random value
   * from the new state.
   *
   * @returns A pseudo-random value in the range `[min(), max()]`.
   */
  public next(): T {
    const type = this.constructor as LinearCongruentialEngineConstructor<T> & typeof LinearCongruentialEngine;

    this.state = (
      (type.multiplier as bigint) * this.state +
      (type.increment as bigint)
    ) % this.actualModulus as T;

    return this.state;
  }

  /**
   * Advances the internal state by `z` times.
   *
   * @param z Integer value specifying the number of times to advance the state.
   */
  public discard(z: UnsignedLongLong): void {
    if (z < 0n || z > UINT64_MAX) {
      throw new RandomError(
        RANDOM_ERROR_CODES.OUT_OF_RANGE,
        'The discard count is outside the unsigned long long range.',
        { z },
      );
    }

    const type = this.constructor as LinearCongruentialEngineConstructor<T> & typeof LinearCongruentialEngine;
    const modulus = this.actualModulus;

    let remaining = z;
    let multiplier = type.multiplier as bigint;
    let increment = type.increment as bigint;
    let accumulatedMultiplier = 1n;
    let accumulatedIncrement = 0n;

    while (remaining > 0n) {
      if ((remaining & 1n) !== 0n) {
        accumulatedIncrement = (multiplier * accumulatedIncrement + increment) % modulus;
        accumulatedMultiplier = (multiplier * accumulatedMultiplier) % modulus;
      }

      increment = (multiplier * increment + increment) % modulus;
      multiplier = (multiplier * multiplier) % modulus;
      remaining >>= 1n;
    }

    this.state = (accumulatedMultiplier * this.state + accumulatedIncrement) % modulus as T;
  }

  /**
   * Compares the internal states of two pseudo-random number engines.
   *
   * @param other Engine to compare.
   * @returns `true` if the internal states are equivalent.
   */
  public equals(other: LinearCongruentialEngine<T>): boolean {
    return this.constructor === other.constructor && this.state === other.state;
  }

  private seedValue(value: T): T {
    const type = this.constructor as LinearCongruentialEngineConstructor<T> & typeof LinearCongruentialEngine;
    const modulus = this.actualModulus
    const state = (value as bigint) % modulus;

    if (
      (type.increment as bigint) % modulus === 0n &&
      state === 0n
    ) {
      return 1n as T;
    }

    return state as T;
  }

  private seedSequence(seq: SeedSequence): void {
    const type = this.constructor as LinearCongruentialEngineConstructor<T> & typeof LinearCongruentialEngine;
    const modulus = this.actualModulus

    const bitLength = (value: bigint): number => value.toString(2).length;
    const k = Math.ceil(bitLength(modulus) / 32);
    const data = Array<SeedResult>(k + 3).fill(0n as UInt32);

    seq.generate(data);

    let state = 0n;

    for (let j = 0; j < k; j += 1) {
      const word = data[j + 3];

      if (word === undefined) {
        throw new RandomError(
          RANDOM_ERROR_CODES.INVALID_SEED_SEQUENCE,
          'The seed sequence did not generate enough values.',
          { index: j + 3 }
        );
      }

      state = (state + (word << BigInt(32 * j))) % modulus;
    }

    if (
      (type.increment as bigint) % modulus === 0n &&
      state === 0n
    ) {
      this.state = 1n as T;
    } else {
      this.state = state as T;
    }
  }

  private getActualModulus(type: LinearCongruentialEngineConstructor<T>): bigint {
    if (type.modulus !== 0n) {
      return type.modulus as bigint;
    }

    return getResultBits(type) === 32 ? UINT32_MAX + 1n : UINT64_MAX + 1n;
  }



  private validateParameters(type: LinearCongruentialEngineConstructor<T> & typeof LinearCongruentialEngine): void {
    const maximum = getResultBits(type) === 32 ? UINT32_MAX : UINT64_MAX;
    const multiplier = type.multiplier as bigint;
    const increment = type.increment as bigint;
    const modulus = type.modulus as bigint;

    if (multiplier < 0n || multiplier > maximum ||
        increment < 0n || increment > maximum ||
        modulus < 0n || modulus > maximum) {
      throw new RandomError(
        RANDOM_ERROR_CODES.OUT_OF_RANGE,
        'The engine parameters are outside the result type range.',
        {
          multiplier,
          increment,
          modulus,
        },
      );
    }

    if (modulus !== 0n && (multiplier >= modulus || increment >= modulus)) {
      throw new RandomError(
        RANDOM_ERROR_CODES.INVALID_ARGUMENT,
        'The multiplier and increment must be less than the modulus.',
        {
          multiplier,
          increment,
          modulus,
        },
      );
    }
  }
}

/**
 * Defines a `LinearCongruentialEngine` specialization.
 *
 * The returned value is a class constructor whose static members represent
 * the parameters of the specialization and whose instances contain the
 * engine state.
 *
 * @typeParam T Result type generated by the engine.
 * @param definition Parameters defining the engine specialization.
 * @returns A `LinearCongruentialEngine` constructor.
 */
export function defineLinearCongruentialEngine<T extends UInt>(
  definition: LinearCongruentialEngineDefinition<T>,
): LinearCongruentialEngineConstructor<T> {
  class Engine extends LinearCongruentialEngine<T> {
    public static readonly multiplier = definition.multiplier;
    public static readonly increment = definition.increment;
    public static readonly modulus = definition.modulus;
    public static readonly defaultSeed = definition.defaultSeed;

    public static override min(): T {
      return (this.increment === 0n ? 1n : 0n) as T;
    }

    public static override max(): T {
      if (this.modulus === 0n) {
        return (definition.resultBits === 32 ? UINT32_MAX : UINT64_MAX) as T;
      }

      return (this.modulus - 1n) as T;
    }
  };

  if (definition.resultBits === 64) {
    resultBits64.add(Engine);
  }

  return Engine;
}
