import type { RandomEngine, SeedSequence, UInt, UnsignedLongLong } from '../typings';
import { RandomError, RandomErrorCode } from '../typings';
import type { IsLessThan } from './bigint';

/**
 * Describes how much the type system knows about the
 * UniformRandomBitGenerator range requirement.
 *
 * `true` means `min() < max()` is known to hold.
 *
 * `false` means `min() < max()` is known not to hold.
 *
 * `'unknown'` means the available type information is insufficient to decide.
 */
export type UniformRandomBitGeneratorStatus = true | false | 'unknown';

/**
 * Type-level range information associated with a random engine.
 *
 * @typeParam Minimum The minimum generated value.
 * @typeParam Maximum The maximum generated value.
 */
export interface RandomEngineTraits<Min extends bigint = bigint, Max extends bigint = bigint> {
  readonly minimum: Min;
  readonly maximum: Max;
}

/**
 * Type-only witness used by factory-defined engines to retain their
 * compile-time engine traits.
 *
 * @internal
 */
declare const randomEngineTraits: unique symbol;

/**
 * Type-only witness used to declare that an external engine satisfies the
 * UniformRandomBitGenerator requirements.
 */
export declare const uniformRandomBitGeneratorStatus: unique symbol;

type UniformRandomBitGeneratorStatusMarker<Status extends UniformRandomBitGeneratorStatus> =
  Status extends true | false
    ? { readonly [uniformRandomBitGeneratorStatus]: Status }
    : {};

/**
 * Type-only diagnostic attached to a rejected engine.
 *
 * Keeping the diagnostic as a named property produces a more useful compiler
 * message than reducing the rejected type to `never`.
 *
 * @internal
 */
interface RandomLibraryConstraintError<Message extends string> {
  readonly __randomLibraryConstraintError: Message;
}

/**
 * Evaluates the UniformRandomBitGenerator range relation from engine traits.
 *
 * @typeParam Traits Type-level engine range information.
 */
export type UniformRandomBitGeneratorStatusFromRandomEngineTraits<Traits extends RandomEngineTraits> =
  [IsLessThan<Traits['minimum'], Traits['maximum']>] extends [true]
    ? true
    : [IsLessThan<Traits['minimum'], Traits['maximum']>] extends [false]
      ? false
      : 'unknown';

/**
 * Extracts the statically known UniformRandomBitGenerator status of an engine.
 *
 * An explicit status declaration takes precedence over automatically derived
 * factory traits.
 *
 * @typeParam Engine The engine type being examined.
 */
export type UniformRandomBitGeneratorStatusOf<Engine extends RandomEngine> =
  Engine extends { readonly [uniformRandomBitGeneratorStatus]: infer Status extends boolean; }
    ? Status
    : Engine extends { readonly [randomEngineTraits]: infer Traits extends RandomEngineTraits; }
      ? UniformRandomBitGeneratorStatusFromRandomEngineTraits<Traits>
      : 'unknown';

/**
 * Type-only engine witness carrying compile-time specialization information.
 *
 * Factory-defined engines use this type to preserve the exact range derived
 * from their specialization parameters.
 *
 * @typeParam Type Result type produced by the engine.
 * @typeParam Traits Derived engine traits.
 *
 * @internal
 */
export type TypedRandomEngine<Type extends UInt, Traits extends RandomEngineTraits> =
  RandomEngine<Type> &
  { readonly [randomEngineTraits]: Traits } &
  UniformRandomBitGeneratorStatusMarker<
    UniformRandomBitGeneratorStatusFromRandomEngineTraits<Traits>
  >;

/**
 * Represents the C++ UniformRandomBitGenerator concept
 *
 * The following behavior is intentional:
 *
 * - a known-valid engine is accepted;
 * - an unknown external engine is accepted;
 * - an engine known to violate `min() < max()` is rejected.
 *
 * `Engine` is the concrete engine type being constrained.
 *
 * `Type` is the result type produced by the engine and is inferred from
 * `Engine` when omitted.
 *
 * @typeParam Engine The engine type being constrained.
 * @typeParam Type The result type generated by the engine.
 */
export type UniformRandomBitGenerator<Engine extends RandomEngine, Type extends UInt = RandomEngineResultType<Engine>> =
  [UniformRandomBitGeneratorStatusOf<Engine>] extends [false]
    ? Engine & RandomLibraryConstraintError<
        'The engine is known not to satisfy UniformRandomBitGenerator because min() is not less than max.'
      >
    : Engine & RandomEngine<Type>;

/**
 * Extracts the result type of a random engine.
 *
 * @typeParam Engine The engine type being examined.
 */
export type RandomEngineResultType<Engine extends RandomEngine> =
  Engine extends RandomEngine<infer Result> ? Result : never;

/**
 * Represents an explicitly proven UniformRandomBitGenerator.
 *
 * @typeParam Engine The concrete engine type.
 * @typeParam Type The result type generated by the engine.
 */
export type KnownUniformRandomBitGenerator<
  Engine extends RandomEngine,
  Type extends UInt = RandomEngineResultType<Engine>,
> =
  Engine & RandomEngine<Type> & {
    readonly [uniformRandomBitGeneratorStatus]: true;
  };

/**
 * Structural constructor requirements for a random engine.
 *
 * @typeParam Type The result type generated by the engine.
 */
export interface RandomEngineConstructor<Type extends UInt = UInt> {
  new (...args: any[]): RandomEngine<Type>;
}

/**
 * Structural constructor requirements needed to inspect the
 * UniformRandomBitGenerator range.
 *
 * @typeParam Type The result type generated by the engine.
 */
export interface UniformRandomBitGeneratorConstructor<Type extends UInt = UInt>
  extends RandomEngineConstructor<Type> {
  min(): Type;
  max(): Type;
}

/**
 * The additional state-management requirements of a RandomNumberEngine.
 *
 * @typeParam Engine The concrete engine type.
 * @typeParam Type The result type generated by the engine.
 *
 * @internal
 */
type RandomNumberEngineRequirements<
  Engine extends RandomEngine,
  Type extends UInt = RandomEngineResultType<Engine>,
> = {
  seed(): void;
  seed(value: Type): void;
  seed(sequence: SeedSequence): void;
  discard(count: UnsignedLongLong): void;
  equals(other: Engine): boolean;
};

/**
 * Represents the C++-style RandomNumberEngine requirements.
 *
 * A RandomNumberEngine is a known-valid UniformRandomBitGenerator with the
 * engine state-management operations required by this library.
 *
 * Unlike UniformRandomBitGenerator, an unknown engine is rejected here because
 * this stronger concept requires a known-valid UniformRandomBitGenerator.
 *
 * `Engine` is the concrete engine type. This makes the type useful for engine
 * adaptors that need to refer to their underlying engine.
 *
 * @typeParam Engine The concrete engine type.
 * @typeParam Type The result type generated by the engine.
 */
export type RandomNumberEngine<Engine extends RandomEngine, Type extends UInt = RandomEngineResultType<Engine>> =
  [UniformRandomBitGeneratorStatusOf<Engine>] extends [true]
    ? Engine & RandomEngine<Type> & RandomNumberEngineRequirements<Engine, Type>
    : [UniformRandomBitGeneratorStatusOf<Engine>] extends [false]
      ? Engine & RandomLibraryConstraintError<
          'The engine is known not to satisfy RandomNumberEngine because min() is not less than max.'
        >
      : Engine & RandomLibraryConstraintError<
          'The engine has unknown UniformRandomBitGenerator status and cannot satisfy RandomNumberEngine.'
        >;

/**
 * A RandomNumberEngine type produced after runtime validation.
 *
 * @typeParam Engine The original engine type.
 * @typeParam Type The result type generated by the engine.
 */
export type ValidatedRandomNumberEngine<Engine extends RandomEngine, Type extends UInt = RandomEngineResultType<Engine>> =
  Engine &
  RandomEngine<Type> &
  { readonly [uniformRandomBitGeneratorStatus]: true } &
  RandomNumberEngineRequirements<Engine, Type>;

/**
 * Runtime-validates the observable UniformRandomBitGenerator requirements of
 * an external engine.
 *
 * Normal UniformRandomBitGenerator APIs do not require callers to invoke this
 * function.
 *
 * The check verifies that static `min()` and `max()` exist and that
 * `min() < max()`.
 *
 * @param engine The engine to validate.
 * @throws {RandomError} If static range functions are missing or invalid.
 */
export function assertUniformRandomBitGenerator<Engine extends RandomEngine>(engine: Engine): asserts engine is KnownUniformRandomBitGenerator<Engine> {
  const constructor = engine.constructor as Partial<UniformRandomBitGeneratorConstructor<UInt>>;

  if (typeof constructor.min !== 'function' || typeof constructor.max !== 'function') {
    throw new RandomError(
      RandomErrorCode.INVALID_ARGUMENT,
      'The engine does not provide static min() and max().',
    );
  }

  const minimum = constructor.min();
  const maximum = constructor.max();

  if (
    typeof minimum !== 'bigint' ||
    typeof maximum !== 'bigint' ||
    minimum < 0n ||
    maximum < 0n ||
    minimum >= maximum
  ) {
    throw new RandomError(
      RandomErrorCode.INVALID_ARGUMENT,
      'The engine does not satisfy the UniformRandomBitGenerator range requirement.',
      { minimum, maximum },
    );
  }
}

/**
 * Runtime-validates and returns the same object as a known
 * UniformRandomBitGenerator.
 *
 * No wrapper object is created.
 *
 * @param engine The engine to validate.
 * @returns The same engine object with a compile-time proof marker.
 */
export function toUniformRandomBitGenerator<Engine extends RandomEngine>(engine: Engine): KnownUniformRandomBitGenerator<Engine> {
  assertUniformRandomBitGenerator(engine);
  return engine;
}

/**
 * Runtime-validates the observable RandomNumberEngine requirements of an
 * external engine.
 *
 * This first validates the UniformRandomBitGenerator range requirement and
 * then checks `seed()`, `discard()`, and `equals()`.
 *
 * @param engine The engine to validate.
 * @throws {RandomError} If the engine does not satisfy the observable
 * requirements.
 */
export function assertRandomNumberEngine<Engine extends RandomEngine>(
  engine: Engine,
): asserts engine is ValidatedRandomNumberEngine<Engine> {
  assertUniformRandomBitGenerator(engine);

  const candidate = engine as Engine & {
    seed?: unknown;
    discard?: unknown;
    equals?: unknown;
  };

  if (typeof candidate.seed !== 'function' ||
      typeof candidate.discard !== 'function' ||
      typeof candidate.equals !== 'function') {
    throw new RandomError(
      RandomErrorCode.INVALID_ARGUMENT,
      'The engine does not provide the RandomNumberEngine state-management operations.',
    );
  }
}

/**
 * Runtime-validates and returns the same object as a RandomNumberEngine.
 *
 * No wrapper object is created.
 *
 * @param engine The engine to validate.
 * @returns The same engine object with compile-time RandomNumberEngine requirements.
 */
export function toRandomNumberEngine<Engine extends RandomEngine>(engine: Engine): ValidatedRandomNumberEngine<Engine> {
  assertRandomNumberEngine(engine);
  return engine;
}
